// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class builder wrappers for type-safe field access.

/// Wrapper for the `ProposalContent` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ProposalContentClassBuilder {
    inner: baml::ClassBuilder,
}

impl ProposalContentClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner
            .as_type()
            .expect("ProposalContent is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `intro_paragraph` field builder.
    pub fn property_intro_paragraph(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("intro_paragraph")
            .expect("ProposalContent.intro_paragraph is statically defined in .baml and should always be present")
    }

    /// Access the `tier_narratives` field builder.
    pub fn property_tier_narratives(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tier_narratives")
            .expect("ProposalContent.tier_narratives is statically defined in .baml and should always be present")
    }

    /// Access the `zone_callouts` field builder.
    pub fn property_zone_callouts(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("zone_callouts")
            .expect("ProposalContent.zone_callouts is statically defined in .baml and should always be present")
    }

    /// Access the `closing_paragraph` field builder.
    pub fn property_closing_paragraph(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("closing_paragraph")
            .expect("ProposalContent.closing_paragraph is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `TierInput` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct TierInputClassBuilder {
    inner: baml::ClassBuilder,
}

impl TierInputClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner
            .as_type()
            .expect("TierInput is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `tier_level` field builder.
    pub fn property_tier_level(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tier_level").expect(
            "TierInput.tier_level is statically defined in .baml and should always be present",
        )
    }

    /// Access the `total` field builder.
    pub fn property_total(&self) -> baml::ClassPropertyBuilder {
        self.inner
            .get_property("total")
            .expect("TierInput.total is statically defined in .baml and should always be present")
    }

    /// Access the `zones` field builder.
    pub fn property_zones(&self) -> baml::ClassPropertyBuilder {
        self.inner
            .get_property("zones")
            .expect("TierInput.zones is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `TierNarrative` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct TierNarrativeClassBuilder {
    inner: baml::ClassBuilder,
}

impl TierNarrativeClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner
            .as_type()
            .expect("TierNarrative is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `tier_level` field builder.
    pub fn property_tier_level(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tier_level").expect(
            "TierNarrative.tier_level is statically defined in .baml and should always be present",
        )
    }

    /// Access the `headline` field builder.
    pub fn property_headline(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("headline").expect(
            "TierNarrative.headline is statically defined in .baml and should always be present",
        )
    }

    /// Access the `description` field builder.
    pub fn property_description(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("description").expect(
            "TierNarrative.description is statically defined in .baml and should always be present",
        )
    }

    /// Access the `differentiators` field builder.
    pub fn property_differentiators(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("differentiators")
            .expect("TierNarrative.differentiators is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `ZoneCallout` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ZoneCalloutClassBuilder {
    inner: baml::ClassBuilder,
}

impl ZoneCalloutClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner
            .as_type()
            .expect("ZoneCallout is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `zone_label` field builder.
    pub fn property_zone_label(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("zone_label").expect(
            "ZoneCallout.zone_label is statically defined in .baml and should always be present",
        )
    }

    /// Access the `note` field builder.
    pub fn property_note(&self) -> baml::ClassPropertyBuilder {
        self.inner
            .get_property("note")
            .expect("ZoneCallout.note is statically defined in .baml and should always be present")
    }
}

/// Wrapper for the `ZoneSummary` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ZoneSummaryClassBuilder {
    inner: baml::ClassBuilder,
}

impl ZoneSummaryClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner
            .as_type()
            .expect("ZoneSummary is statically defined in .baml and should always have a type")
    }

    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================

    /// Access the `label` field builder.
    pub fn property_label(&self) -> baml::ClassPropertyBuilder {
        self.inner
            .get_property("label")
            .expect("ZoneSummary.label is statically defined in .baml and should always be present")
    }

    /// Access the `zone_type` field builder.
    pub fn property_zone_type(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("zone_type").expect(
            "ZoneSummary.zone_type is statically defined in .baml and should always be present",
        )
    }

    /// Access the `area_sqft` field builder.
    pub fn property_area_sqft(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("area_sqft").expect(
            "ZoneSummary.area_sqft is statically defined in .baml and should always be present",
        )
    }

    /// Access the `materials` field builder.
    pub fn property_materials(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("materials").expect(
            "ZoneSummary.materials is statically defined in .baml and should always be present",
        )
    }
}
