// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated TypeBuilder wrappers for type-safe schema access.

mod classes;
mod enums;

pub use classes::*;
pub use enums::*;

use std::sync::Arc;

/// TypeBuilder for dynamic type construction.
///
/// This wrapper provides access to the BAML TypeBuilder for creating
/// dynamic types at runtime. Use `TypeBuilder::new()` to create an instance.
///
/// Access schema-defined classes and enums via methods:
/// - `tb.ClassName()` returns the class builder
/// - `tb.EnumName()` returns the enum builder
#[derive(Clone)]
pub struct TypeBuilder {
    inner: Arc<baml::TypeBuilder>,
}

impl TypeBuilder {
    /// Create a new TypeBuilder for dynamic type construction.
    ///
    /// # Example
    /// ```ignore
    /// let tb = TypeBuilder::new();
    /// let my_enum = tb.add_enum("MyDynamicEnum")?;
    /// my_enum.add_value("Option1")?;
    /// ```
    pub fn new() -> Self {
        Self {
            inner: Arc::new(super::runtime::get_runtime().new_type_builder()),
        }
    }

    /// Get reference to inner TypeBuilder for FFI calls.
    pub(crate) fn inner(&self) -> &baml::TypeBuilder {
        &self.inner
    }

    // =========================================================================
    // Schema Class Accessors (1:1 with schema class names)
    // =========================================================================

    /// Access the `ClassifiedFeature` class builder.
    pub fn ClassifiedFeature(&self) -> ClassifiedFeatureClassBuilder {
        ClassifiedFeatureClassBuilder::new(
            self.inner
                .get_class("ClassifiedFeature")
                .expect("class ClassifiedFeature is defined in schema"),
        )
    }

    /// Access the `Discrepancy` class builder.
    pub fn Discrepancy(&self) -> DiscrepancyClassBuilder {
        DiscrepancyClassBuilder::new(
            self.inner
                .get_class("Discrepancy")
                .expect("class Discrepancy is defined in schema"),
        )
    }

    /// Access the `FeatureCandidateInput` class builder.
    pub fn FeatureCandidateInput(&self) -> FeatureCandidateInputClassBuilder {
        FeatureCandidateInputClassBuilder::new(
            self.inner
                .get_class("FeatureCandidateInput")
                .expect("class FeatureCandidateInput is defined in schema"),
        )
    }

    /// Access the `PlantSelection` class builder.
    pub fn PlantSelection(&self) -> PlantSelectionClassBuilder {
        PlantSelectionClassBuilder::new(
            self.inner
                .get_class("PlantSelection")
                .expect("class PlantSelection is defined in schema"),
        )
    }

    /// Access the `PlanterEstimate` class builder.
    pub fn PlanterEstimate(&self) -> PlanterEstimateClassBuilder {
        PlanterEstimateClassBuilder::new(
            self.inner
                .get_class("PlanterEstimate")
                .expect("class PlanterEstimate is defined in schema"),
        )
    }

    /// Access the `PlanterStyle` class builder.
    pub fn PlanterStyle(&self) -> PlanterStyleClassBuilder {
        PlanterStyleClassBuilder::new(
            self.inner
                .get_class("PlanterStyle")
                .expect("class PlanterStyle is defined in schema"),
        )
    }

    /// Access the `ProposalContent` class builder.
    pub fn ProposalContent(&self) -> ProposalContentClassBuilder {
        ProposalContentClassBuilder::new(
            self.inner
                .get_class("ProposalContent")
                .expect("class ProposalContent is defined in schema"),
        )
    }

    /// Access the `RecommendedZone` class builder.
    pub fn RecommendedZone(&self) -> RecommendedZoneClassBuilder {
        RecommendedZoneClassBuilder::new(
            self.inner
                .get_class("RecommendedZone")
                .expect("class RecommendedZone is defined in schema"),
        )
    }

    /// Access the `ReconciledFeature` class builder.
    pub fn ReconciledFeature(&self) -> ReconciledFeatureClassBuilder {
        ReconciledFeatureClassBuilder::new(
            self.inner
                .get_class("ReconciledFeature")
                .expect("class ReconciledFeature is defined in schema"),
        )
    }

    /// Access the `ReconciledSite` class builder.
    pub fn ReconciledSite(&self) -> ReconciledSiteClassBuilder {
        ReconciledSiteClassBuilder::new(
            self.inner
                .get_class("ReconciledSite")
                .expect("class ReconciledSite is defined in schema"),
        )
    }

    /// Access the `SatelliteBaseline` class builder.
    pub fn SatelliteBaseline(&self) -> SatelliteBaselineClassBuilder {
        SatelliteBaselineClassBuilder::new(
            self.inner
                .get_class("SatelliteBaseline")
                .expect("class SatelliteBaseline is defined in schema"),
        )
    }

    /// Access the `SatelliteTree` class builder.
    pub fn SatelliteTree(&self) -> SatelliteTreeClassBuilder {
        SatelliteTreeClassBuilder::new(
            self.inner
                .get_class("SatelliteTree")
                .expect("class SatelliteTree is defined in schema"),
        )
    }

    /// Access the `SiteAnalysis` class builder.
    pub fn SiteAnalysis(&self) -> SiteAnalysisClassBuilder {
        SiteAnalysisClassBuilder::new(
            self.inner
                .get_class("SiteAnalysis")
                .expect("class SiteAnalysis is defined in schema"),
        )
    }

    /// Access the `SiteObservation` class builder.
    pub fn SiteObservation(&self) -> SiteObservationClassBuilder {
        SiteObservationClassBuilder::new(
            self.inner
                .get_class("SiteObservation")
                .expect("class SiteObservation is defined in schema"),
        )
    }

    /// Access the `SuggestedZone` class builder.
    pub fn SuggestedZone(&self) -> SuggestedZoneClassBuilder {
        SuggestedZoneClassBuilder::new(
            self.inner
                .get_class("SuggestedZone")
                .expect("class SuggestedZone is defined in schema"),
        )
    }

    /// Access the `TierInput` class builder.
    pub fn TierInput(&self) -> TierInputClassBuilder {
        TierInputClassBuilder::new(
            self.inner
                .get_class("TierInput")
                .expect("class TierInput is defined in schema"),
        )
    }

    /// Access the `TierNarrative` class builder.
    pub fn TierNarrative(&self) -> TierNarrativeClassBuilder {
        TierNarrativeClassBuilder::new(
            self.inner
                .get_class("TierNarrative")
                .expect("class TierNarrative is defined in schema"),
        )
    }

    /// Access the `ZoneCallout` class builder.
    pub fn ZoneCallout(&self) -> ZoneCalloutClassBuilder {
        ZoneCalloutClassBuilder::new(
            self.inner
                .get_class("ZoneCallout")
                .expect("class ZoneCallout is defined in schema"),
        )
    }

    /// Access the `ZoneSummary` class builder.
    pub fn ZoneSummary(&self) -> ZoneSummaryClassBuilder {
        ZoneSummaryClassBuilder::new(
            self.inner
                .get_class("ZoneSummary")
                .expect("class ZoneSummary is defined in schema"),
        )
    }

    // =========================================================================
    // Schema Enum Accessors (1:1 with schema enum names)
    // =========================================================================

    // =========================================================================
    // Primitive Types (all infallible)
    // =========================================================================

    /// Get the string type.
    pub fn string(&self) -> baml::TypeDef {
        self.inner.string()
    }

    /// Get the int type.
    pub fn int(&self) -> baml::TypeDef {
        self.inner.int()
    }

    /// Get the float type.
    pub fn float(&self) -> baml::TypeDef {
        self.inner.float()
    }

    /// Get the bool type.
    pub fn bool(&self) -> baml::TypeDef {
        self.inner.bool()
    }

    /// Get the null type.
    pub fn null(&self) -> baml::TypeDef {
        self.inner.null()
    }

    // =========================================================================
    // Literal Types (all infallible)
    // =========================================================================

    /// Create a literal string type.
    pub fn literal_string(&self, value: &str) -> baml::TypeDef {
        self.inner.literal_string(value)
    }

    /// Create a literal int type.
    pub fn literal_int(&self, value: i64) -> baml::TypeDef {
        self.inner.literal_int(value)
    }

    /// Create a literal bool type.
    pub fn literal_bool(&self, value: bool) -> baml::TypeDef {
        self.inner.literal_bool(value)
    }

    // =========================================================================
    // Composite Types (all infallible)
    // =========================================================================

    /// Create a list type.
    pub fn list(&self, inner: &baml::TypeDef) -> baml::TypeDef {
        self.inner.list(inner)
    }

    /// Create an optional type.
    pub fn optional(&self, inner: &baml::TypeDef) -> baml::TypeDef {
        self.inner.optional(inner)
    }

    /// Create a map type.
    pub fn map(&self, key: &baml::TypeDef, value: &baml::TypeDef) -> baml::TypeDef {
        self.inner.map(key, value)
    }

    /// Create a union type.
    pub fn union(&self, types: &[&baml::TypeDef]) -> baml::TypeDef {
        self.inner.union(types)
    }

    // =========================================================================
    // Schema Operations (fallible)
    // =========================================================================

    /// Add BAML schema definitions.
    pub fn add_baml(&self, baml_source: &str) -> Result<(), baml::BamlError> {
        self.inner.add_baml(baml_source)
    }

    /// Print the TypeBuilder state for debugging.
    pub fn print(&self) -> String {
        self.inner.print()
    }

    // =========================================================================
    // Dynamic Enum Operations
    // =========================================================================

    /// Add a new dynamic enum.
    pub fn add_enum(&self, name: &str) -> Result<baml::EnumBuilder, baml::BamlError> {
        self.inner.add_enum(name)
    }

    /// Get an enum by name (returns None if not found).
    pub fn get_enum(&self, name: &str) -> Option<baml::EnumBuilder> {
        self.inner.get_enum(name)
    }

    /// List all enums.
    pub fn list_enums(&self) -> Vec<baml::EnumBuilder> {
        self.inner.list_enums()
    }

    // =========================================================================
    // Dynamic Class Operations
    // =========================================================================

    /// Add a new dynamic class.
    pub fn add_class(&self, name: &str) -> Result<baml::ClassBuilder, baml::BamlError> {
        self.inner.add_class(name)
    }

    /// Get a class by name (returns None if not found).
    pub fn get_class(&self, name: &str) -> Option<baml::ClassBuilder> {
        self.inner.get_class(name)
    }

    /// List all classes.
    pub fn list_classes(&self) -> Vec<baml::ClassBuilder> {
        self.inner.list_classes()
    }
}

impl Default for TypeBuilder {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Debug for TypeBuilder {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TypeBuilder")
            .field("state", &self.print())
            .finish()
    }
}
