// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class types.

use super::*;
use baml::{BamlDecode, BamlEncode};

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ProposalContent {
    pub intro_paragraph: String,

    pub tier_narratives: Vec<TierNarrative>,

    pub zone_callouts: Vec<ZoneCallout>,

    pub closing_paragraph: String,
}

impl AsRef<ProposalContent> for ProposalContent {
    fn as_ref(&self) -> &ProposalContent {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct TierInput {
    pub tier_level: String,

    pub total: String,

    pub zones: Vec<ZoneSummary>,
}

impl AsRef<TierInput> for TierInput {
    fn as_ref(&self) -> &TierInput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct TierNarrative {
    pub tier_level: String,

    pub headline: String,

    pub description: String,

    pub differentiators: Vec<String>,
}

impl AsRef<TierNarrative> for TierNarrative {
    fn as_ref(&self) -> &TierNarrative {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ZoneCallout {
    pub zone_label: String,

    pub note: String,
}

impl AsRef<ZoneCallout> for ZoneCallout {
    fn as_ref(&self) -> &ZoneCallout {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ZoneSummary {
    pub label: String,

    pub zone_type: String,

    pub area_sqft: f64,

    pub materials: Vec<String>,
}

impl AsRef<ZoneSummary> for ZoneSummary {
    fn as_ref(&self) -> &ZoneSummary {
        self
    }
}
