// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class types.

use super::*;
use baml::{BamlDecode, BamlEncode};

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ClassifiedFeature {
    pub cluster_id: i64,

    pub label: String,

    pub category: String,

    pub species: Option<String>,

    pub confidence: f64,

    pub reasoning: String,

    pub landscape_notes: String,
}

impl AsRef<ClassifiedFeature> for ClassifiedFeature {
    fn as_ref(&self) -> &ClassifiedFeature {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct Discrepancy {
    pub description: String,

    pub possible_explanation: String,

    pub design_implication: String,
}

impl AsRef<Discrepancy> for Discrepancy {
    fn as_ref(&self) -> &Discrepancy {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct FeatureCandidateInput {
    pub cluster_id: i64,

    pub centroid_x: f64,

    pub centroid_y: f64,

    pub centroid_z: f64,

    pub height_ft: f64,

    pub spread_ft: f64,

    pub point_count: i64,

    pub dominant_color: String,

    pub vertical_profile: String,

    pub density: f64,
}

impl AsRef<FeatureCandidateInput> for FeatureCandidateInput {
    fn as_ref(&self) -> &FeatureCandidateInput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct PlantSelection {
    pub common_name: String,

    pub botanical_name: String,

    pub spacing_inches: f64,

    pub why_this_plant: String,
}

impl AsRef<PlantSelection> for PlantSelection {
    fn as_ref(&self) -> &PlantSelection {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct PlanterEstimate {
    pub styles: Vec<PlanterStyle>,
}

impl AsRef<PlanterEstimate> for PlanterEstimate {
    fn as_ref(&self) -> &PlanterEstimate {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct PlanterStyle {
    pub style_name: String,

    pub description: String,

    pub plant_selections: Vec<PlantSelection>,

    pub soil_depth_inches: f64,

    pub design_rationale: String,
}

impl AsRef<PlanterStyle> for PlanterStyle {
    fn as_ref(&self) -> &PlanterStyle {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ProposalContent {
    pub intro_paragraph: String,

    pub tier_narratives: Vec<TierNarrative>,

    pub zone_callouts: Vec<ZoneCallout>,

    pub closing_paragraph: String,
}

impl AsRef<ProposalContent> for ProposalContent {
    fn as_ref(&self) -> &ProposalContent {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct RecommendedZone {
    pub label: String,

    pub zone_type: String,

    pub rationale: String,

    pub approximate_area_sqft: f64,

    pub sun_exposure_hours: Option<i64>,

    pub data_sources: String,
}

impl AsRef<RecommendedZone> for RecommendedZone {
    fn as_ref(&self) -> &RecommendedZone {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ReconciledFeature {
    pub label: String,

    pub category: String,

    pub source: String,

    pub confidence: f64,

    pub reasoning: String,
}

impl AsRef<ReconciledFeature> for ReconciledFeature {
    fn as_ref(&self) -> &ReconciledFeature {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ReconciledSite {
    pub confirmed_features: Vec<ReconciledFeature>,

    pub scan_only_features: Vec<ReconciledFeature>,

    pub satellite_only_features: Vec<ReconciledFeature>,

    pub discrepancies: Vec<Discrepancy>,

    pub recommended_zones: Vec<RecommendedZone>,
}

impl AsRef<ReconciledSite> for ReconciledSite {
    fn as_ref(&self) -> &ReconciledSite {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct SatelliteBaseline {
    pub lot_area_sqft: f64,

    pub trees: Vec<SatelliteTree>,

    pub avg_sun_hours: f64,
}

impl AsRef<SatelliteBaseline> for SatelliteBaseline {
    fn as_ref(&self) -> &SatelliteBaseline {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct SatelliteTree {
    pub height_ft: f64,

    pub spread_ft: f64,

    pub confidence: f64,
}

impl AsRef<SatelliteTree> for SatelliteTree {
    fn as_ref(&self) -> &SatelliteTree {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct SiteAnalysis {
    pub features: Vec<ClassifiedFeature>,

    pub suggested_zones: Vec<SuggestedZone>,

    pub site_observations: Vec<SiteObservation>,
}

impl AsRef<SiteAnalysis> for SiteAnalysis {
    fn as_ref(&self) -> &SiteAnalysis {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct SiteObservation {
    pub observation: String,
}

impl AsRef<SiteObservation> for SiteObservation {
    fn as_ref(&self) -> &SiteObservation {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct SuggestedZone {
    pub label: String,

    pub zone_type: String,

    pub rationale: String,

    pub approximate_area_sqft: f64,
}

impl AsRef<SuggestedZone> for SuggestedZone {
    fn as_ref(&self) -> &SuggestedZone {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct TierInput {
    pub tier_level: String,

    pub total: String,

    pub zones: Vec<ZoneSummary>,
}

impl AsRef<TierInput> for TierInput {
    fn as_ref(&self) -> &TierInput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct TierNarrative {
    pub tier_level: String,

    pub headline: String,

    pub description: String,

    pub differentiators: Vec<String>,
}

impl AsRef<TierNarrative> for TierNarrative {
    fn as_ref(&self) -> &TierNarrative {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ZoneCallout {
    pub zone_label: String,

    pub note: String,
}

impl AsRef<ZoneCallout> for ZoneCallout {
    fn as_ref(&self) -> &ZoneCallout {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ZoneSummary {
    pub label: String,

    pub zone_type: String,

    pub area_sqft: f64,

    pub materials: Vec<String>,
}

impl AsRef<ZoneSummary> for ZoneSummary {
    fn as_ref(&self) -> &ZoneSummary {
        self
    }
}
