// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated BAML types.

mod classes;
mod enums;
mod unions;
mod type_aliases;

pub use classes::*;
pub use enums::*;
pub use unions::*;
pub use type_aliases::*;

// Re-export types from baml runtime
pub use baml::{Audio, Image, Pdf, Video};
pub use baml::{Checked, StreamState};

/// All known types in this BAML project.
/// Serves as the compile-time type registry for BamlValue.
#[derive(Debug, Clone)]
pub enum Types {

    ClassifiedFeature(ClassifiedFeature),

    Discrepancy(Discrepancy),

    FeatureCandidateInput(FeatureCandidateInput),

    PlantSelection(PlantSelection),

    PlanterEstimate(PlanterEstimate),

    PlanterStyle(PlanterStyle),

    ProposalContent(ProposalContent),

    RecommendedZone(RecommendedZone),

    ReconciledFeature(ReconciledFeature),

    ReconciledSite(ReconciledSite),

    SatelliteBaseline(SatelliteBaseline),

    SatelliteTree(SatelliteTree),

    SiteAnalysis(SiteAnalysis),

    SiteObservation(SiteObservation),

    SuggestedZone(SuggestedZone),

    TierInput(TierInput),

    TierNarrative(TierNarrative),

    ZoneCallout(ZoneCallout),

    ZoneSummary(ZoneSummary),



}

impl baml::KnownTypes for Types {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {

            Types::ClassifiedFeature(_) => "ClassifiedFeature",

            Types::Discrepancy(_) => "Discrepancy",

            Types::FeatureCandidateInput(_) => "FeatureCandidateInput",

            Types::PlantSelection(_) => "PlantSelection",

            Types::PlanterEstimate(_) => "PlanterEstimate",

            Types::PlanterStyle(_) => "PlanterStyle",

            Types::ProposalContent(_) => "ProposalContent",

            Types::RecommendedZone(_) => "RecommendedZone",

            Types::ReconciledFeature(_) => "ReconciledFeature",

            Types::ReconciledSite(_) => "ReconciledSite",

            Types::SatelliteBaseline(_) => "SatelliteBaseline",

            Types::SatelliteTree(_) => "SatelliteTree",

            Types::SiteAnalysis(_) => "SiteAnalysis",

            Types::SiteObservation(_) => "SiteObservation",

            Types::SuggestedZone(_) => "SuggestedZone",

            Types::TierInput(_) => "TierInput",

            Types::TierNarrative(_) => "TierNarrative",

            Types::ZoneCallout(_) => "ZoneCallout",

            Types::ZoneSummary(_) => "ZoneSummary",




        }
    }
}