// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming class types.
//!
//! These types are used during streaming to hold partial results.
//! Field types are already wrapped appropriately (Option, StreamState, etc.)

use super::*;
use crate::baml_client::types;
use baml::BamlDecode;

#[derive(Debug, Clone, Default, BamlDecode)]

pub struct ProposalContent {
    pub intro_paragraph: Option<String>,

    pub tier_narratives: Vec<TierNarrative>,

    pub zone_callouts: Vec<ZoneCallout>,

    pub closing_paragraph: Option<String>,
}

impl AsRef<ProposalContent> for ProposalContent {
    fn as_ref(&self) -> &ProposalContent {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode)]

pub struct TierInput {
    pub tier_level: Option<String>,

    pub total: Option<String>,

    pub zones: Vec<ZoneSummary>,
}

impl AsRef<TierInput> for TierInput {
    fn as_ref(&self) -> &TierInput {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode)]

pub struct TierNarrative {
    pub tier_level: Option<String>,

    pub headline: Option<String>,

    pub description: Option<String>,

    pub differentiators: Vec<String>,
}

impl AsRef<TierNarrative> for TierNarrative {
    fn as_ref(&self) -> &TierNarrative {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode)]

pub struct ZoneCallout {
    pub zone_label: Option<String>,

    pub note: Option<String>,
}

impl AsRef<ZoneCallout> for ZoneCallout {
    fn as_ref(&self) -> &ZoneCallout {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode)]

pub struct ZoneSummary {
    pub label: Option<String>,

    pub zone_type: Option<String>,

    pub area_sqft: Option<f64>,

    pub materials: Vec<String>,
}

impl AsRef<ZoneSummary> for ZoneSummary {
    fn as_ref(&self) -> &ZoneSummary {
        self
    }
}
