// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated streaming class types.
//!
//! These types are used during streaming to hold partial results.
//! Field types are already wrapped appropriately (Option, StreamState, etc.)

use baml::BamlDecode;
use crate::baml_client::types;
use super::*;





#[derive(Debug, Clone, Default, BamlDecode)]

pub struct ClassifiedFeature {



    pub cluster_id: Option<i64>,



    pub label: Option<String>,



    pub category: Option<String>,



    pub species: Option<String>,



    pub confidence: Option<f64>,



    pub reasoning: Option<String>,



    pub landscape_notes: Option<String>,


}



impl AsRef<ClassifiedFeature> for ClassifiedFeature {
    fn as_ref(&self) -> &ClassifiedFeature {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct Discrepancy {



    pub description: Option<String>,



    pub possible_explanation: Option<String>,



    pub design_implication: Option<String>,


}



impl AsRef<Discrepancy> for Discrepancy {
    fn as_ref(&self) -> &Discrepancy {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct FeatureCandidateInput {



    pub cluster_id: Option<i64>,



    pub centroid_x: Option<f64>,



    pub centroid_y: Option<f64>,



    pub centroid_z: Option<f64>,



    pub height_ft: Option<f64>,



    pub spread_ft: Option<f64>,



    pub point_count: Option<i64>,



    pub dominant_color: Option<String>,



    pub vertical_profile: Option<String>,



    pub density: Option<f64>,


}



impl AsRef<FeatureCandidateInput> for FeatureCandidateInput {
    fn as_ref(&self) -> &FeatureCandidateInput {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct PlantSelection {



    pub common_name: Option<String>,



    pub botanical_name: Option<String>,



    pub spacing_inches: Option<f64>,



    pub why_this_plant: Option<String>,


}



impl AsRef<PlantSelection> for PlantSelection {
    fn as_ref(&self) -> &PlantSelection {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct PlanterEstimate {



    pub styles: Vec<PlanterStyle>,


}



impl AsRef<PlanterEstimate> for PlanterEstimate {
    fn as_ref(&self) -> &PlanterEstimate {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct PlanterStyle {



    pub style_name: Option<String>,



    pub description: Option<String>,



    pub plant_selections: Vec<PlantSelection>,



    pub soil_depth_inches: Option<f64>,



    pub design_rationale: Option<String>,


}



impl AsRef<PlanterStyle> for PlanterStyle {
    fn as_ref(&self) -> &PlanterStyle {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct ProposalContent {



    pub intro_paragraph: Option<String>,



    pub tier_narratives: Vec<TierNarrative>,



    pub zone_callouts: Vec<ZoneCallout>,



    pub closing_paragraph: Option<String>,


}



impl AsRef<ProposalContent> for ProposalContent {
    fn as_ref(&self) -> &ProposalContent {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct RecommendedZone {



    pub label: Option<String>,



    pub zone_type: Option<String>,



    pub rationale: Option<String>,



    pub approximate_area_sqft: Option<f64>,



    pub sun_exposure_hours: Option<i64>,



    pub data_sources: Option<String>,


}



impl AsRef<RecommendedZone> for RecommendedZone {
    fn as_ref(&self) -> &RecommendedZone {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct ReconciledFeature {



    pub label: Option<String>,



    pub category: Option<String>,



    pub source: Option<String>,



    pub confidence: Option<f64>,



    pub reasoning: Option<String>,


}



impl AsRef<ReconciledFeature> for ReconciledFeature {
    fn as_ref(&self) -> &ReconciledFeature {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct ReconciledSite {



    pub confirmed_features: Vec<ReconciledFeature>,



    pub scan_only_features: Vec<ReconciledFeature>,



    pub satellite_only_features: Vec<ReconciledFeature>,



    pub discrepancies: Vec<Discrepancy>,



    pub recommended_zones: Vec<RecommendedZone>,


}



impl AsRef<ReconciledSite> for ReconciledSite {
    fn as_ref(&self) -> &ReconciledSite {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct SatelliteBaseline {



    pub lot_area_sqft: Option<f64>,



    pub trees: Vec<SatelliteTree>,



    pub avg_sun_hours: Option<f64>,


}



impl AsRef<SatelliteBaseline> for SatelliteBaseline {
    fn as_ref(&self) -> &SatelliteBaseline {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct SatelliteTree {



    pub height_ft: Option<f64>,



    pub spread_ft: Option<f64>,



    pub confidence: Option<f64>,


}



impl AsRef<SatelliteTree> for SatelliteTree {
    fn as_ref(&self) -> &SatelliteTree {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct SiteAnalysis {



    pub features: Vec<ClassifiedFeature>,



    pub suggested_zones: Vec<SuggestedZone>,



    pub site_observations: Vec<SiteObservation>,


}



impl AsRef<SiteAnalysis> for SiteAnalysis {
    fn as_ref(&self) -> &SiteAnalysis {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct SiteObservation {



    pub observation: Option<String>,


}



impl AsRef<SiteObservation> for SiteObservation {
    fn as_ref(&self) -> &SiteObservation {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct SuggestedZone {



    pub label: Option<String>,



    pub zone_type: Option<String>,



    pub rationale: Option<String>,



    pub approximate_area_sqft: Option<f64>,


}



impl AsRef<SuggestedZone> for SuggestedZone {
    fn as_ref(&self) -> &SuggestedZone {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct TierInput {



    pub tier_level: Option<String>,



    pub total: Option<String>,



    pub zones: Vec<ZoneSummary>,


}



impl AsRef<TierInput> for TierInput {
    fn as_ref(&self) -> &TierInput {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct TierNarrative {



    pub tier_level: Option<String>,



    pub headline: Option<String>,



    pub description: Option<String>,



    pub differentiators: Vec<String>,


}



impl AsRef<TierNarrative> for TierNarrative {
    fn as_ref(&self) -> &TierNarrative {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct ZoneCallout {



    pub zone_label: Option<String>,



    pub note: Option<String>,


}



impl AsRef<ZoneCallout> for ZoneCallout {
    fn as_ref(&self) -> &ZoneCallout {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct ZoneSummary {



    pub label: Option<String>,



    pub zone_type: Option<String>,



    pub area_sqft: Option<f64>,



    pub materials: Vec<String>,


}



impl AsRef<ZoneSummary> for ZoneSummary {
    fn as_ref(&self) -> &ZoneSummary {
        self
    }
}

