// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming types (partial data during streaming).
//!
//! Full implementation coming in Phase 6.

mod classes;
mod type_aliases;
mod unions;

pub use classes::*;
pub use type_aliases::*;
pub use unions::*;

/// Streaming variants of types (all fields Optional).
#[derive(Debug, Clone)]
pub enum StreamTypes {
    ClassifiedFeature(ClassifiedFeature),

    FeatureCandidateInput(FeatureCandidateInput),

    PlantSelection(PlantSelection),

    PlanterEstimate(PlanterEstimate),

    PlanterStyle(PlanterStyle),

    ProposalContent(ProposalContent),

    SiteAnalysis(SiteAnalysis),

    SiteObservation(SiteObservation),

    SuggestedZone(SuggestedZone),

    TierInput(TierInput),

    TierNarrative(TierNarrative),

    ZoneCallout(ZoneCallout),

    ZoneSummary(ZoneSummary),
}

impl baml::KnownTypes for StreamTypes {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {
            StreamTypes::ClassifiedFeature(_) => "ClassifiedFeature",

            StreamTypes::FeatureCandidateInput(_) => "FeatureCandidateInput",

            StreamTypes::PlantSelection(_) => "PlantSelection",

            StreamTypes::PlanterEstimate(_) => "PlanterEstimate",

            StreamTypes::PlanterStyle(_) => "PlanterStyle",

            StreamTypes::ProposalContent(_) => "ProposalContent",

            StreamTypes::SiteAnalysis(_) => "SiteAnalysis",

            StreamTypes::SiteObservation(_) => "SiteObservation",

            StreamTypes::SuggestedZone(_) => "SuggestedZone",

            StreamTypes::TierInput(_) => "TierInput",

            StreamTypes::TierNarrative(_) => "TierNarrative",

            StreamTypes::ZoneCallout(_) => "ZoneCallout",

            StreamTypes::ZoneSummary(_) => "ZoneSummary",
        }
    }
}
