// Plantastic — Branded Landscape Proposal Template
// Data arrives as JSON string via sys.inputs.data

#let data = json(bytes(sys.inputs.data))

// ── Page setup ───────────────────────────────────────────────────

#set page(
  paper: "us-letter",
  margin: (top: 1in, bottom: 1in, left: 0.75in, right: 0.75in),
  footer: context [
    #set text(8pt, fill: luma(120))
    #h(1fr) Generated by Plantastic #h(1fr)
    Page #counter(page).display("1 of 1", both: true)
  ],
)

#set text(font: "New Computer Modern", size: 10pt)
#set par(justify: true, leading: 0.65em)

// ── Accent color ─────────────────────────────────────────────────

#let accent = if data.branding.primary_color != none {
  rgb(data.branding.primary_color)
} else {
  rgb("#2E7D32")
}

// ── Header ───────────────────────────────────────────────────────

#align(center)[
  #text(18pt, weight: "bold", fill: accent)[#data.branding.company_name]
]

#v(2pt)

#align(center)[
  #set text(9pt, fill: luma(80))
  #if data.branding.phone != none [#data.branding.phone]
  #if data.branding.phone != none and data.branding.email != none [ · ]
  #if data.branding.email != none [#data.branding.email]
]

#v(6pt)
#line(length: 100%, stroke: 0.5pt + accent)
#v(6pt)

// ── Project info ─────────────────────────────────────────────────

#grid(
  columns: (1fr, auto),
  align: (left, right),
  [
    #text(14pt, weight: "bold")[Landscape Proposal]
    #v(2pt)
    #text(11pt)[#data.project_name]
    #v(1pt)
    #text(9pt, fill: luma(80))[#data.project_address]
  ],
  [
    #text(10pt, fill: luma(80))[#data.date]
  ],
)

#v(12pt)

// ── Intro paragraph ──────────────────────────────────────────────

#data.narrative.intro_paragraph

#v(16pt)

// ── Three-tier comparison table ──────────────────────────────────

#text(13pt, weight: "bold", fill: accent)[Investment Options]

#v(8pt)

// Build a unified table: one row per zone per line-item, with columns for each tier.
// We'll show a simplified comparison with per-tier totals.

#{
  // Collect all unique zones across tiers (use Good tier as canonical ordering)
  let good = data.tiers.at(0)
  let better = data.tiers.at(1)
  let best = data.tiers.at(2)

  // Helper: find line items for a given zone label in a tier
  let find_items(tier, zone_label) = {
    tier.line_items.filter(it => it.zone_label == zone_label)
  }

  // Get unique zone labels in order from Good tier
  let zone_labels = good.line_items.map(it => it.zone_label).dedup()

  // Table header
  let header = table.header(
    table.cell(fill: accent.lighten(85%), text(weight: "bold")[Zone / Material]),
    table.cell(fill: accent.lighten(85%), align(center, text(weight: "bold")[Good])),
    table.cell(fill: accent.lighten(85%), align(center, text(weight: "bold")[Better])),
    table.cell(fill: accent.lighten(85%), align(center, text(weight: "bold")[Best])),
  )

  // Build rows
  let rows = ()
  for zone_label in zone_labels {
    // Zone header row
    rows.push(table.cell(colspan: 4, fill: luma(245), text(weight: "bold", size: 9pt)[#zone_label]))

    // Get items for this zone in each tier
    let g_items = find_items(good, zone_label)
    let b_items = find_items(better, zone_label)
    let bt_items = find_items(best, zone_label)

    // Find max number of line items across tiers for this zone
    let max_items = calc.max(g_items.len(), b_items.len(), bt_items.len())

    for i in range(max_items) {
      let g = if i < g_items.len() { g_items.at(i) } else { none }
      let b = if i < b_items.len() { b_items.at(i) } else { none }
      let bt = if i < bt_items.len() { bt_items.at(i) } else { none }

      let mat_name = if g != none { g.material_name } else if b != none { b.material_name } else { bt.material_name }

      rows.push(text(size: 9pt)[#h(8pt)#mat_name])
      rows.push(align(center, text(size: 9pt)[#{if g != none { g.line_total } else { "—" }}]))
      rows.push(align(center, text(size: 9pt)[#{if b != none { b.line_total } else { "—" }}]))
      rows.push(align(center, text(size: 9pt)[#{if bt != none { bt.line_total } else { "—" }}]))
    }
  }

  // Subtotal row
  rows.push(table.cell(fill: luma(240), align(right, text(weight: "bold", size: 9pt)[Subtotal])))
  rows.push(table.cell(fill: luma(240), align(center, text(weight: "bold", size: 9pt)[#good.subtotal])))
  rows.push(table.cell(fill: luma(240), align(center, text(weight: "bold", size: 9pt)[#better.subtotal])))
  rows.push(table.cell(fill: luma(240), align(center, text(weight: "bold", size: 9pt)[#best.subtotal])))

  // Tax row (if present)
  if good.tax != none {
    rows.push(table.cell(align(right, text(size: 9pt)[Tax])))
    rows.push(align(center, text(size: 9pt)[#good.tax]))
    rows.push(align(center, text(size: 9pt)[#better.tax]))
    rows.push(align(center, text(size: 9pt)[#best.tax]))
  }

  // Grand total row
  rows.push(table.cell(fill: accent.lighten(90%), align(right, text(weight: "bold", size: 10pt)[Total])))
  rows.push(table.cell(fill: accent.lighten(90%), align(center, text(weight: "bold", size: 10pt, fill: accent)[#good.total])))
  rows.push(table.cell(fill: accent.lighten(90%), align(center, text(weight: "bold", size: 10pt, fill: accent)[#better.total])))
  rows.push(table.cell(fill: accent.lighten(90%), align(center, text(weight: "bold", size: 10pt, fill: accent)[#best.total])))

  table(
    columns: (1fr, auto, auto, auto),
    column-gutter: 0pt,
    stroke: 0.5pt + luma(200),
    inset: 6pt,
    header,
    ..rows,
  )
}

#v(16pt)

// ── Tier narratives ──────────────────────────────────────────────

#for narrative in data.tier_narratives [
  #text(12pt, weight: "bold", fill: accent)[#narrative.headline]
  #v(4pt)
  #narrative.description
  #v(4pt)
  #for diff in narrative.differentiators [
    - #diff
  ]
  #v(10pt)
]

// ── Zone callouts ────────────────────────────────────────────────

#if data.zone_callouts.len() > 0 [
  #text(13pt, weight: "bold", fill: accent)[Zone Details]
  #v(8pt)

  #for callout in data.zone_callouts [
    #text(10pt, weight: "bold")[#callout.zone_label]
    #v(2pt)
    #text(9pt)[#callout.note]
    #v(8pt)
  ]
]

// ── Closing ──────────────────────────────────────────────────────

#v(8pt)
#line(length: 100%, stroke: 0.5pt + luma(200))
#v(8pt)

#data.closing_paragraph

#v(12pt)
#align(center)[
  #text(11pt, weight: "bold", fill: accent)[Ready to get started? Contact us today!]
  #v(4pt)
  #set text(9pt, fill: luma(80))
  #if data.branding.phone != none [#data.branding.phone]
  #if data.branding.phone != none and data.branding.email != none [ · ]
  #if data.branding.email != none [#data.branding.email]
]
